[mongodb]
mongodb.chikoo.fun

[redis]
redis.chikoo.fun

[mysql]
mysql.chikoo.fun

[rabbitmq]
rabbitmq.chikoo.fun

[catalogue]
catalogue.chikoo.fun

[cart]
cart.chikoo.fun

[user]
user.chikoo.fun

[shipping]
shipping.chikoo.fun

[payment]
payment.chikoo.fun

[frontend]
frontend.chikoo.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321