- name: disable nginx module
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: remove html directory
  ansible.builtin.file:
    state: absent
    path: /usr/share/nginx/html/

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download frontend app zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Unzip file already existing on the remote server
  ansible.builtin.unarchive:
    src: /tmp/fontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove nginx conf
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/nginx.conf

- name: copy nginx conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
