- name: install sql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: sql service enable and start
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
    - botocore
    - boto3

- name: set root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
