- name: disable node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable node js
  ansible.builtin.command: dnf module disable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Create a new user roboshop
  ansible.builtin.user:
    name: roboshop
    comment: "roboshop system user"
    system: true
    shell: /sbin/nologin
    home: /app
    state: present

- name: remove directory if exists
  ansible.builtin.file:
    path: /app
    state: absent

- name: create a app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue app zip file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Unzip file already existing on the remote server
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: copy catalogue service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb command line
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh mongodb.chikoo.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host mongodb.chikoo.fun </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd  reload config files
  ansible.builtin.systemd_service:
    name: catalogue
    state: started
    enabled: true
    daemon_reload: true
